spring:
  application:
    name: medical-rag-publisher

medicalai:
  openfda:
    api:
      base-url: ${FDA_API_BASE_URL:https://api.fda.gov}
    ingestion:
      enabled: ${FDA_INGESTION_ENABLED:true}
      limit: ${FDA_INGESTION_LIMIT:1}
      skip: ${FDA_INGESTION_SKIP:0}