spring:
  application:
    name: medical-rag-publisher

  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: mxbai-embed-large
    vectorstore:
      qdrant:
        host: ${QDRANT_URL:localhost}
        port: 6334
        collection-name: medical-agent-rag
#        api-key: ${QDRANT_API_KEY}

medicalai:
  openfda:
    api:
      base-url: ${FDA_API_BASE_URL:https://api.fda.gov}
    ingestion:
      enabled: ${FDA_INGESTION_ENABLED:false}
      limit: ${FDA_INGESTION_LIMIT:1}
      skip: ${FDA_INGESTION_SKIP:0}
  vector:
    publish: true